# Generated by Django 4.2.1 on 2023-06-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discapacidad', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
